name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Run ruff linter and formatter
      uses: astral-sh/ruff-action@v3

    - name: Install and run mypy
      run: |
        pip install mypy
        mypy --strict vies.py

    - name: Run doctests
      run: |
        python -m doctest vies.py
